/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PresentIndexRouteImport } from './routes/present/index'
import { Route as SCodeRouteImport } from './routes/s.$code'
import { Route as PresentCodeRouteImport } from './routes/present/$code'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentIndexRoute = PresentIndexRouteImport.update({
  id: '/present/',
  path: '/present/',
  getParentRoute: () => rootRouteImport,
} as any)
const SCodeRoute = SCodeRouteImport.update({
  id: '/s/$code',
  path: '/s/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentCodeRoute = PresentCodeRouteImport.update({
  id: '/present/$code',
  path: '/present/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/present/$code': typeof PresentCodeRoute
  '/s/$code': typeof SCodeRoute
  '/present/': typeof PresentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/present/$code': typeof PresentCodeRoute
  '/s/$code': typeof SCodeRoute
  '/present': typeof PresentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/present/$code': typeof PresentCodeRoute
  '/s/$code': typeof SCodeRoute
  '/present/': typeof PresentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/join' | '/present/$code' | '/s/$code' | '/present/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/join' | '/present/$code' | '/s/$code' | '/present'
  id: '__root__' | '/' | '/join' | '/present/$code' | '/s/$code' | '/present/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRoute
  PresentCodeRoute: typeof PresentCodeRoute
  SCodeRoute: typeof SCodeRoute
  PresentIndexRoute: typeof PresentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present/': {
      id: '/present/'
      path: '/present'
      fullPath: '/present/'
      preLoaderRoute: typeof PresentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$code': {
      id: '/s/$code'
      path: '/s/$code'
      fullPath: '/s/$code'
      preLoaderRoute: typeof SCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present/$code': {
      id: '/present/$code'
      path: '/present/$code'
      fullPath: '/present/$code'
      preLoaderRoute: typeof PresentCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  PresentCodeRoute: PresentCodeRoute,
  SCodeRoute: SCodeRoute,
  PresentIndexRoute: PresentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
